server:
  port: ${SERVER.PORT:8090}
  timeout: ${SERVER.TIMEOUT:10}

api:
  ExhibitCreate:
    method: POST
    url: exhibit
  ExhibitRead:
    method: GET
    url: exhibit/{id}
  ExhibitsRead:
    method: GET
    url: exhibit
  ExhibitUpdate:
    method: PUT
    url: exhibit/{id}
  ExhibitDelete:
    method: DELETE
    url: exhibit/{id}

  NewsCreate:
    method: POST
    url: news
  NewsReadSingle:
    method: GET
    url: news/{id}
  NewsRead:
    method: GET
    url: news
  NewsUpdate:
    method: PUT
    url: news/{id}
  NewsDelete:
    method: DELETE
    url: news/{id}
