server:
  port: ${SERVER.PORT:8090}
  timeout: ${SERVER.TIMEOUT:10}

api:
  NewsCreate:
    method: POST
    url: news
  NewsReadSingle:
    method: GET
    url: news/{id}
  NewsRead:
    method: GET
    url: news
  NewsUpdate:
    method: PUT
    url: news/{id}
  NewsDelete:
    method: DELETE
    url: news/{id}
